INSERT INTO t_p61203256_auto_catalog_site.products (slug,name,category,price,old_price,mount,install,warranty,year_from,year_to,badge,fits,sort_order) VALUES
('tow-01','Фаркоп съёмный, шар типа A','Фаркопы',14900,17400,'6 штатных точек лонжерона','2,5 часа','5 лет',2015,2026,'Хит','{"Lada":["Vesta SW Cross","Granta","Niva Travel","Largus"],"Kia":["Rio","Sportage","Seltos"],"Hyundai":["Creta","Solaris","Tucson"],"Renault":["Duster","Logan","Kaptur"]}'::jsonb,10),
('tow-02','Фаркоп усиленный, нагрузка 2000 кг','Фаркопы',23400,NULL,'8 штатных точек рамы','3 часа','5 лет',2012,2026,NULL,'{"Toyota":["Land Cruiser Prado","RAV4"],"Volkswagen":["Tiguan","Touareg","Teramont"],"Hyundai":["Santa Fe","Tucson"]}'::jsonb,20),
('tow-03','Розетка фаркопа 7-pin с блоком согласования','Электроника',4800,NULL,'штатный разъём проводки','1 час','2 года',2014,2026,NULL,'{"Lada":["Vesta SW Cross","Granta","Niva Travel","Largus","XRAY"],"Kia":["Rio","Sportage","Seltos","Ceed"],"Toyota":["RAV4","Camry","Corolla"],"Hyundai":["Creta","Solaris"],"Volkswagen":["Polo","Tiguan"],"Renault":["Duster","Logan","Arkana","Kaptur"]}'::jsonb,30),
('rail-01','Рейлинги продольные, алюминий','Багажники',11200,13000,'4 штатных точки в крыше','1,5 часа','3 года',2016,2026,'Акция','{"Lada":["Vesta SW Cross","Niva Travel","Largus","XRAY"],"Renault":["Duster","Kaptur"],"Hyundai":["Creta","Tucson"],"Kia":["Sportage","Seltos"]}'::jsonb,40),
('rail-02','Поперечины на рейлинги, замок','Багажники',7600,NULL,'на рейлинг, без сверления','30 минут','3 года',2010,2026,NULL,'{"Lada":["Vesta SW Cross","Niva Travel","Largus"],"Toyota":["RAV4","Land Cruiser Prado"],"Volkswagen":["Tiguan","Touareg","Teramont"],"Kia":["Sportage","Seltos","Ceed"],"Hyundai":["Creta","Tucson","Santa Fe"],"Renault":["Duster","Kaptur","Arkana"]}'::jsonb,50),
('rail-03','Бокс на крышу 430 л, двустороннее открытие','Багажники',32900,NULL,'на поперечины','20 минут','3 года',2010,2026,NULL,'{"Lada":["Vesta SW Cross","Niva Travel","Largus"],"Toyota":["RAV4","Land Cruiser Prado","Camry"],"Volkswagen":["Tiguan","Touareg","Teramont"],"Kia":["Sportage","Seltos"],"Hyundai":["Creta","Tucson","Santa Fe"],"Renault":["Duster","Kaptur"]}'::jsonb,60),
('step-01','Пороги-подножки Ø60, нержавейка','Пороги',15800,NULL,'6 штатных точек порога','2 часа','5 лет',2014,2026,NULL,'{"Toyota":["RAV4","Land Cruiser Prado"],"Volkswagen":["Tiguan","Touareg","Teramont"],"Kia":["Sportage","Seltos"],"Hyundai":["Tucson","Santa Fe","Creta"],"Renault":["Duster","Kaptur"],"Lada":["Niva Travel"]}'::jsonb,70),
('step-02','Накладки на пороги с подсветкой','Салон',3900,NULL,'штатный проём двери','40 минут','1 год',2015,2026,NULL,'{"Lada":["Vesta SW Cross","Granta","XRAY","Largus"],"Kia":["Rio","Ceed","Seltos"],"Hyundai":["Solaris","Creta"],"Volkswagen":["Polo","Tiguan"]}'::jsonb,80),
('prot-01','Защита картера, сталь 2 мм','Защита',6700,8100,'4 штатных точки подрамника','1 час','3 года',2012,2026,'Акция','{"Lada":["Vesta SW Cross","Granta","Niva Travel","Largus","XRAY"],"Kia":["Rio","Sportage","Seltos","Ceed"],"Hyundai":["Creta","Solaris","Tucson"],"Volkswagen":["Polo","Tiguan"],"Renault":["Duster","Logan","Arkana","Kaptur"],"Toyota":["RAV4","Camry","Corolla"]}'::jsonb,90),
('prot-02','Защита картера композит, 5 кг','Защита',12400,NULL,'4 штатных точки подрамника','1 час','3 года',2018,2026,NULL,'{"Toyota":["RAV4","Camry"],"Volkswagen":["Tiguan","Teramont"],"Kia":["Seltos","Sportage"],"Hyundai":["Tucson","Santa Fe"]}'::jsonb,100),
('int-01','Коврики 3D с бортом, полиуретан','Салон',5400,NULL,'штатные пистоны крепления','10 минут','2 года',2012,2026,'Хит','{"Lada":["Vesta SW Cross","Granta","Niva Travel","Largus","XRAY"],"Toyota":["RAV4","Camry","Corolla","Land Cruiser Prado"],"Kia":["Rio","Sportage","Seltos","Ceed"],"Hyundai":["Creta","Solaris","Tucson","Santa Fe"],"Volkswagen":["Polo","Tiguan","Touareg","Teramont"],"Renault":["Duster","Logan","Arkana","Kaptur"]}'::jsonb,110),
('int-02','Органайзер в багажник по размеру ниши','Салон',4300,NULL,'штатная ниша багажника','5 минут','1 год',2014,2026,NULL,'{"Lada":["Vesta SW Cross","Largus","Niva Travel"],"Kia":["Rio","Seltos"],"Hyundai":["Creta","Solaris"],"Renault":["Duster","Arkana"]}'::jsonb,120),
('el-01','Парктроник задний, 4 датчика','Электроника',8900,NULL,'бампер + штатная проводка','2 часа','2 года',2010,2026,NULL,'{"Lada":["Vesta SW Cross","Granta","Niva Travel","Largus","XRAY"],"Kia":["Rio","Ceed"],"Hyundai":["Solaris"],"Renault":["Duster","Logan"],"Volkswagen":["Polo"]}'::jsonb,130),
('el-02','Камера заднего вида в штатную ручку','Электроника',6300,7500,'штатное место подсветки номера','1,5 часа','2 года',2013,2026,'Акция','{"Lada":["Vesta SW Cross","Granta","XRAY"],"Kia":["Rio","Ceed","Sportage"],"Hyundai":["Solaris","Creta"],"Volkswagen":["Polo","Tiguan"],"Toyota":["Camry","Corolla"],"Renault":["Logan","Duster"]}'::jsonb,140),
('el-03','Автозапуск с подогревом по таймеру','Электроника',19700,NULL,'штатная CAN-шина','4 часа','3 года',2016,2026,NULL,'{"Toyota":["RAV4","Camry","Corolla","Land Cruiser Prado"],"Kia":["Sportage","Seltos","Ceed"],"Hyundai":["Creta","Tucson","Santa Fe"],"Volkswagen":["Tiguan","Teramont","Touareg"],"Lada":["Vesta SW Cross"]}'::jsonb,150),
('prot-03','Брызговики по форме арки, комплект','Защита',2600,NULL,'штатные отверстия арки','30 минут','1 год',2010,2026,NULL,'{"Lada":["Vesta SW Cross","Granta","Niva Travel","Largus","XRAY"],"Kia":["Rio","Sportage","Seltos","Ceed"],"Hyundai":["Creta","Solaris","Tucson","Santa Fe"],"Volkswagen":["Polo","Tiguan","Touareg","Teramont"],"Renault":["Duster","Logan","Arkana","Kaptur"],"Toyota":["RAV4","Camry","Corolla","Land Cruiser Prado"]}'::jsonb,160)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO t_p61203256_auto_catalog_site.brands (name,models,sort_order) VALUES
('Lada','["Vesta SW Cross","Granta","Niva Travel","Largus","XRAY"]'::jsonb,10),
('Toyota','["RAV4","Camry","Land Cruiser Prado","Corolla"]'::jsonb,20),
('Kia','["Rio","Sportage","Seltos","Ceed"]'::jsonb,30),
('Hyundai','["Creta","Solaris","Tucson","Santa Fe"]'::jsonb,40),
('Volkswagen','["Polo","Tiguan","Touareg","Teramont"]'::jsonb,50),
('Renault','["Duster","Logan","Arkana","Kaptur"]'::jsonb,60)
ON CONFLICT (name) DO NOTHING;
