-- Семь проводок остались без марок и моделей, поэтому подбор не показывал
-- их вообще ни одной машине. В названии марка есть — переносим её в привязку.
-- Где названа конкретная модель (Ford F150, Haval H8) — привязываем точечно,
-- где только марка («Ford 2002-2016») — все модели марки, как уже сделано
-- у остальных проводок каталога. Годы у товаров не трогаем.
UPDATE products SET fits='{"FIAT": ["Argo", "Bravo", "Cronos", "Doblo", "Ducato", "Egea", "Fiorino", "Mobi", "Palio", "Panda", "Pulse", "Punto", "Sedici", "Stilo", "Strada", "Tipo", "Uno", "124 Spider", "500", "500L", "500X", "600"]}'::jsonb, fit_mode='vehicle' WHERE sku='GW-KFT01';
UPDATE products SET fits='{"Ford": ["B-Max", "Bronco", "Bronco Sport", "C-Max", "Capri", "Cougar", "Crown Victoria", "EcoSport", "Edge", "Escape", "Escort", "Evos", "Expedition", "Explorer", "F-150", "F-Series", "Falcon", "Fiesta", "Figo", "Flex", "Focus", "Fusion", "Galaxy", "GT", "GT40", "Ka", "Kuga", "Maverick", "Model A", "Mondeo", "Mustang", "Mustang Mach-E", "Orion", "Puma", "Ranger", "S-Max", "Taurus", "Territory", "Thunderbird", "Tourneo", "Transit"]}'::jsonb, fit_mode='vehicle' WHERE sku='GW-KFR14';
UPDATE products SET fits='{"Ford": ["B-Max", "Bronco", "Bronco Sport", "C-Max", "Capri", "Cougar", "Crown Victoria", "EcoSport", "Edge", "Escape", "Escort", "Evos", "Expedition", "Explorer", "F-150", "F-Series", "Falcon", "Fiesta", "Figo", "Flex", "Focus", "Fusion", "Galaxy", "GT", "GT40", "Ka", "Kuga", "Maverick", "Model A", "Mondeo", "Mustang", "Mustang Mach-E", "Orion", "Puma", "Ranger", "S-Max", "Taurus", "Territory", "Thunderbird", "Tourneo", "Transit"]}'::jsonb, fit_mode='vehicle' WHERE sku='GW-KFR09';
UPDATE products SET fits='{"Ford": ["F-150", "F-Series"]}'::jsonb, fit_mode='vehicle' WHERE sku='GW-KFR21';
UPDATE products SET fits='{"Haval": ["H8"]}'::jsonb, fit_mode='vehicle' WHERE sku='GW-KHV03';
UPDATE products SET fits='{"Hyundai": ["Accent", "Alcazar", "Avante", "Azera", "Bayon", "Casper", "Coupe", "Creta", "Custo", "Elantra", "Equus", "Excel", "Galloper", "Genesis", "Getz", "Grandeur", "H-1", "H1", "H350", "HD", "i20", "i30", "i40", "Ioniq", "Ioniq 5", "Ioniq 6", "Ioniq 9", "IX25", "ix35", "ix45", "ix55", "Kona", "Lantra", "Matrix", "Nexo", "Palisade", "Pony", "Porter", "Santa Fe", "Scoupe", "Solaris", "Sonata", "Starex", "Stargazer", "Staria", "Stellar", "Terracan", "Tiburon", "Tucson", "Tuscani", "Veloster", "Venue", "Veracruz", "Xcient"], "Kia": ["Amanti", "Bongo", "Borrego", "Cadenza", "Carens", "Carnival", "Ceed", "Cerato", "EV3", "EV4", "EV5", "EV6", "EV9", "Forte", "K2500", "K3", "K4", "K5", "K7", "K9", "Magentis", "Mentor", "Mohave", "Morning", "Niro", "Opirus", "Optima", "Picanto", "Pride", "ProCeed", "Quoris", "Ray", "Rio", "Rondo", "Seltos", "Sephia", "Shuma", "Sonet", "Sorento", "Sorento Prime", "Soul", "Spectra", "Sportage", "Stinger", "Stonic", "Telluride", "Venga", "XCeed"]}'::jsonb, fit_mode='vehicle' WHERE sku='GW-KKI11-2';
UPDATE products SET fits='{"Volvo": ["C30", "C70", "S40", "S60", "S80", "S90", "V40", "V60", "V70", "V90", "XC60", "XC70", "XC90"]}'::jsonb, fit_mode='vehicle' WHERE sku='GW-KVO01';
